<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Stella.Utils\Stella.Utils.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Stella.DeviceIdentifier\Stella.DeviceIdentifier.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
