<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Stella.Utils\Stella.Utils.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Stella.DeviceIdentifier\Stella.DeviceIdentifier.csproj" />
    <ProjectReference Include="..\..\Core\Stella.Core\Stella.Core.csproj" />
    <ProjectReference Include="..\..\Core\Stella.Core.Reshade\Stella.Core.Reshade.csproj" />
    <ProjectReference Include="..\..\Core\Stella.Core.FpsUnlock\Stella.Core.FpsUnlock.csproj" />
    <ProjectReference Include="..\..\Core\Stella.Core.Migoto\Stella.Core.Migoto.csproj" />
    <ProjectReference Include="..\..\Application\Stella.Services\Stella.Services.csproj" />
    <ProjectReference Include="..\..\Application\Stella.Update\Stella.Update.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
